[package]
name = "kompo_fs"
version.workspace = true
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2.169"
kompo_tree = { path = "../kompo_tree" }
kompo_wrap = { path = "../kompo_wrap" } 
errno = "*"

[dev-dependencies]
kompo_fs_test_data = { path = "./kompo_fs_test_data" }
serial_test = "3"
